Traceback (most recent call last):
  File "/tmp/ipykernel_399010/1227098573.py", line 11, in model_pipeline
    train_loader, valid_loader = get_dataloaders(config=config, root_dir=data_dir, sampling=True)
  File "/tmp/ipykernel_399010/2689088944.py", line 11, in get_dataloaders
    wandb.log("Train data size:", len(train_dataset))
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1828, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1591, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary