Traceback (most recent call last):
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'dropout'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/akshar/Projects/Fraud_Classification/train.py", line 31, in <module>
    model_pipeline(proj_config=wandb_proj, hyperparams=config, data_dir=data_dir, device=device)
  File "/home/akshar/Projects/Fraud_Classification/pipelines/training_pipeline.py", line 21, in model_pipeline
    model, optimizer = get_model_optimizer(config=config, device=device)
  File "/home/akshar/Projects/Fraud_Classification/model_training/create_model.py", line 14, in get_model_optimizer
    nn.Dropout(p=config.dropout, inplace=True),
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'dropout'